// Arcade + Flappy Bruh regression smoke, driven by WebKit through Playwright. Chromium is never launched.
import { webkit } from 'playwright';
const BASE = process.argv[2] || 'http://localhost:8080/';
const browser = await webkit.launch();
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1.5 })).newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(BASE, { waitUntil: 'load' });
await page.waitForTimeout(1200);
const cards = await page.locator('.card, .game-card, a[href*="games/"]').count();
console.log(`1. arcade index loaded, game links: ${cards}`);
await page.goto(`${BASE}games/flappy-bruh/`, { waitUntil: 'load' });
await page.waitForTimeout(1500);
const frame = page.frameLocator('#game-frame');
const canvas = await frame.locator('canvas').count();
const title = await page.title();
console.log(`2. flappy bruh loaded: "${title}", canvas elements: ${canvas}`);
await page.mouse.click(195, 420);
await page.waitForTimeout(400);
await page.keyboard.press('Space');
await page.waitForTimeout(1500);
const alive = (await frame.locator('canvas').count()) > 0 && (await page.evaluate(() => document.readyState === 'complete'));
console.log(`3. after tap and space, page still alive: ${alive}`);
console.log(`4. page errors: ${errors.length ? errors.join(' | ') : 'none'}`);
await browser.close();
const ok = cards > 0 && canvas > 0 && alive && errors.length === 0;
console.log(ok ? '\nFLAPPY SMOKE: PASS' : '\nFLAPPY SMOKE: FAIL');
process.exit(ok ? 0 : 1);
