// Adult life from 18 to 64: home, money, hobbies, health and everyday surprises. Original writing.
import { ev } from './define.js';

const A = ['youngAdult', 'adult', 'middleAge'];
const YA = ['youngAdult'];
const MA = ['adult', 'middleAge'];

export const ADULT_EVENTS = [
  // Leaving the nest and young adulthood
  ev({ id: 'movedOut', category: 'lifeStage', stages: YA, needs: ['notStudent', 'ownPlace'], when: (c) => c.age <= 24, weight: 8, once: true, kind: 'milestone',
    text: 'You moved into a small place of your own. The first night was quiet and thrilling.', effects: { happiness: 3 } }),
  ev({ id: 'firstApartmentTrouble', category: 'asset', stages: YA, needs: ['ownPlace', 'noHome'], cooldown: 5,
    text: 'The heating in your rental broke in the coldest week of the year.', effects: { happiness: -2, health: -1 } }),
  ev({ id: 'cookingFail', category: 'personal', stages: YA, once: true,
    text: 'You tried to cook a fancy dinner and set off the smoke alarm twice. The toast was fine.', effects: { happiness: 1, smarts: 1 } }),
  ev({ id: 'gapYearTravel', category: 'hobby', stages: YA, needs: ['notStudent', 'money'], once: true, weight: 0.7,
    text: 'You spent a few weeks traveling on a shoestring budget and came home with a hundred stories.', effects: { happiness: 5, money: -700, smarts: 2 } }),
  ev({ id: 'oldFriendVisits', category: 'friendship', stages: A, person: 'friend', cooldown: 7, family: 'friendVisit',
    text: (c) => `${c.whoName} came to visit for a weekend, and you stayed up talking like no time had passed.`, effects: { closeness: 6, happiness: 3 } }),
  ev({ id: 'friendWedding', category: 'friendship', stages: A, minAge: 23, person: 'friend', cooldown: 8, weight: 0.8, family: 'friendMilestone',
    text: (c) => `You went to ${c.whoName}'s wedding and gave a speech that made people laugh in the right places.`, effects: { closeness: 4, happiness: 3, money: -120 } }),
  ev({ id: 'friendBaby', category: 'friendship', stages: A, minAge: 25, person: 'friend', cooldown: 8, weight: 0.7, family: 'friendMilestone',
    text: (c) => `${c.whoName} had a baby, and you were one of the first visitors.`, effects: { closeness: 3, happiness: 2 } }),
  ev({ id: 'friendGroupTrip', category: 'friendship', stages: A, needs: ['friends', 'money'], cooldown: 5, family: 'friendVisit',
    text: 'You and your friends rented a cabin for a long weekend and played board games until dawn.', effects: { friends: 4, happiness: 4, money: -200 } }),
  ev({ id: 'friendNeedsHelp', category: 'friendship', stages: A, person: 'friend', cooldown: 6, family: 'friendTrouble',
    text: (c) => `${c.whoName} went through a rough patch, and you were there every week.`, effects: { closeness: 7, happiness: -1 } }),

  // Money and belongings
  ev({ id: 'taxRefund', category: 'finance', stages: A, needs: ['employed'], cooldown: 4, kind: 'positive', family: 'moneyLuck',
    text: 'A tax refund arrived that you had completely forgotten about.', effects: { money: 400, happiness: 2 } }),
  ev({ id: 'surpriseBill', category: 'finance', stages: A, needs: ['ownPlace'], cooldown: 4, family: 'moneyTrouble',
    text: 'An unexpected bill arrived and ate most of the month.', effects: { money: -350, happiness: -2 } }),
  ev({ id: 'foundMoney', category: 'finance', stages: A, cooldown: 8, weight: 0.5, family: 'moneyLuck',
    text: 'You found cash in an old coat pocket. Past you was generous.', effects: { money: 60, happiness: 2 } }),
  ev({ id: 'lostWallet', category: 'finance', stages: ['teen', 'youngAdult', 'adult'], minAge: 14, cooldown: 8, weight: 0.6, family: 'moneyTrouble',
    text: 'You lost your wallet and spent a week replacing cards.', effects: { money: -60, happiness: -2 } }),
  ev({ id: 'budgetSuccess', category: 'finance', stages: A, needs: ['employed'], cooldown: 5, kind: 'positive',
    text: 'You kept a budget for a whole year and finished with more savings than you expected.', effects: { money: 600, smarts: 1, happiness: 2 } }),
  ev({ id: 'carRepair', category: 'asset', stages: A, needs: ['car'], cooldown: 4, family: 'carTrouble',
    text: 'Your car started making a noise that cost a lot to make it stop.', effects: { money: -450, happiness: -2 } }),
  ev({ id: 'carRoadTrip', category: 'hobby', stages: A, needs: ['car'], cooldown: 5, family: 'carFun',
    text: 'You took a spontaneous road trip with the windows down and the music up.', effects: { happiness: 4 } }),
  ev({ id: 'flatTire', category: 'asset', stages: A, needs: ['car'], cooldown: 5, family: 'carTrouble',
    text: 'A flat tire on the highway taught you how to use a jack in the rain.', effects: { happiness: -2, smarts: 1 } }),
  ev({ id: 'homeRepair', category: 'asset', stages: A, needs: ['home'], cooldown: 4, family: 'homeCare',
    text: 'The roof of your home needed repairs after a storm.', effects: { money: -1200, happiness: -2 } }),
  ev({ id: 'homeGarden', category: 'hobby', stages: A, needs: ['home'], cooldown: 5, family: 'homeCare',
    text: 'You planted a garden, and by August you had more tomatoes than friends to give them to.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'housewarming', category: 'friendship', stages: A, needs: ['home', 'friends'], once: true, kind: 'positive',
    text: 'You threw a housewarming party, and someone brought a plant that is still alive.', effects: { friends: 3, happiness: 3, money: -100 } }),
  ev({ id: 'neighborFriend', category: 'friendship', stages: A, needs: ['ownPlace'], cooldown: 8, max: 2,
    text: 'You got to know a neighbor over a shared fence and a borrowed ladder.', effects: { newFriend: true, happiness: 2 } }),
  ev({ id: 'rentIncrease', category: 'finance', stages: A, needs: ['ownPlace', 'noHome'], cooldown: 5, family: 'moneyTrouble',
    text: 'Your landlord raised the rent, and you started looking at listings you could not afford.', effects: { money: -500, happiness: -2 } }),

  // Hobbies and personal growth
  ev({ id: 'newHobbyPhotography', category: 'hobby', stages: A, once: true, family: 'newHobby',
    text: 'You picked up photography and started noticing light everywhere.', effects: { happiness: 3, smarts: 1 } }),
  ev({ id: 'newHobbyRunning', category: 'hobby', stages: A, once: true, family: 'newHobby',
    text: 'You started running in the mornings. The first month was awful; the second was not.', effects: { health: 4, happiness: 2 } }),
  ev({ id: 'newHobbyCooking', category: 'hobby', stages: A, once: true, family: 'newHobby',
    text: 'You got serious about cooking and stopped setting off the smoke alarm.', effects: { happiness: 2, health: 2, smarts: 1 } }),
  ev({ id: 'newHobbyPainting', category: 'hobby', stages: A, once: true, family: 'newHobby',
    text: 'You took up painting. Your first canvas looked like weather; your tenth looked like a lake.', effects: { happiness: 3 } }),
  ev({ id: 'bookClub', category: 'hobby', stages: A, cooldown: 6, max: 2,
    text: 'You joined a book club that argues more about snacks than books.', effects: { smarts: 2, happiness: 2, newFriend: true } }),
  ev({ id: 'marathon', category: 'hobby', stages: A, needs: ['fit'], cooldown: 6, max: 2, kind: 'positive',
    text: 'You finished a half marathon, slowly, and framed the medal.', effects: { health: 3, happiness: 4 } }),
  ev({ id: 'onlineCourse', category: 'education', stages: A, needs: ['notStudent'], cooldown: 5,
    text: 'You finished an online course in your spare time and actually remembered most of it.', effects: { smarts: 3 } }),
  ev({ id: 'languageLearning', category: 'education', stages: A, needs: ['notStudent'], once: true,
    text: 'You started learning a new language and can now order food and apologize fluently.', effects: { smarts: 3, happiness: 1 } }),
  ev({ id: 'volunteeringAdult', category: 'personal', stages: A, cooldown: 5,
    text: 'You spent weekends volunteering at a community kitchen.', effects: { happiness: 3, newFriend: true } }),
  ev({ id: 'quietYear', category: 'personal', stages: A, cooldown: 6, weight: 0.6,
    text: 'It was a quiet year. Nothing big happened, and that was fine.', effects: { happiness: 1 } }),

  // Health in adult life
  ev({ id: 'badCold', category: 'health', stages: A, cooldown: 4, weight: 0.8, family: 'minorIllness',
    text: 'A stubborn cold knocked you out for a week.', effects: { health: -2, happiness: -1 } }),
  ev({ id: 'backPain', category: 'health', stages: MA, cooldown: 5, weight: 0.8, family: 'minorIllness',
    text: 'Your back started complaining about the way you sit.', effects: { health: -2 } }),
  ev({ id: 'healthScareResolved', category: 'health', stages: MA, cooldown: 8, weight: 0.6,
    text: 'A worrying test result turned out to be nothing serious, and you promised to take better care of yourself.', effects: { health: 2, happiness: -1 } }),
  ev({ id: 'checkupReminder', category: 'health', stages: MA, needs: ['unfit'], cooldown: 4,
    text: 'Your doctor gave you a frank talk about your health.', effects: { happiness: -2, smarts: 1 } }),
  ev({ id: 'goodSleep', category: 'health', stages: A, cooldown: 5,
    text: 'You fixed your sleep schedule this year and felt years younger.', effects: { health: 3, happiness: 2 } }),
  ev({ id: 'readingGlasses', category: 'health', stages: ['middleAge'], once: true,
    text: 'You started holding menus farther away and finally bought reading glasses.', effects: { smarts: 1 } }),
  ev({ id: 'greyHair', category: 'personal', stages: ['middleAge'], once: true,
    text: 'You found your first grey hairs and decided they looked distinguished.', effects: { looks: -1 } }),
  ev({ id: 'midlifeReflection', category: 'personal', stages: ['middleAge'], once: true,
    text: 'You looked back at your life so far and felt mostly proud of it.', effects: { happiness: 2 } }),
  ev({ id: 'hometownVisit', category: 'personal', stages: MA, cooldown: 8,
    text: 'You visited your hometown and found the school much smaller than you remembered.', effects: { happiness: 2 } }),
  ev({ id: 'highSchoolReunion', category: 'friendship', stages: MA, needs: ['graduate'], cooldown: 10, max: 2,
    text: 'Your high school reunion was full of people who had not changed at all.', effects: { happiness: 3, newFriend: true } }),
  ev({ id: 'parentsVisitAdult', category: 'family', stages: A, person: 'parent', cooldown: 4, family: 'parentContact',
    text: (c) => `${c.whoName} visited for a week and reorganized your kitchen.`, effects: { closeness: 5, happiness: 2 } }),
  ev({ id: 'parentCall', category: 'family', stages: A, person: 'parent', cooldown: 3, family: 'parentContact',
    text: (c) => `You started calling ${c.whoName} every Sunday.`, effects: { closeness: 4, happiness: 2 } }),
  ev({ id: 'parentHealthScare', category: 'family', stages: MA, person: 'parent', cooldown: 6, weight: 0.7, family: 'parentHealth',
    text: (c) => `${c.whoName} spent a few days in the hospital and came home tired but recovering.`, effects: { happiness: -4, closeness: 4 } }),
  ev({ id: 'siblingVisit', category: 'family', stages: A, person: 'sibling', cooldown: 5,
    text: (c) => `${c.whoName} stayed with you for a week. You argued about the dishes like old times.`, effects: { closeness: 5, happiness: 2 } }),
  ev({ id: 'familyReunion', category: 'family', stages: A, needs: ['parents'], cooldown: 7,
    text: 'The whole family gathered for a reunion with far too much food.', effects: { family: 3, happiness: 3 } }),
  ev({ id: 'petAdventure', category: 'family', stages: A, person: 'pet', cooldown: 4,
    text: (c) => `${c.who.name} escaped for an afternoon and came home covered in mud, very pleased.`, effects: { closeness: 3, happiness: 1 } }),
  ev({ id: 'jobOfferFriend', category: 'career', stages: A, needs: ['unemployedAdult'], person: 'friend', cooldown: 5,
    text: (c) => `${c.whoName} mentioned an opening where they work. You promised to look at the job board.`, effects: { happiness: 2, closeness: 2 } }),
  ev({ id: 'communityAward', category: 'personal', stages: MA, needs: ['happy'], once: true, weight: 0.5, kind: 'positive',
    text: 'The neighborhood association gave you an award for years of quietly helping out.', effects: { happiness: 4 } }),
];
