// Working life: coworkers, bosses, good years and bad ones. Requires a job. Original writing.
import { ev } from './define.js';

export const CAREER_EVENTS = [
  ev({ id: 'firstPaycheck', category: 'career', needs: ['employed'], weight: 8, once: true, kind: 'positive',
    text: 'Your first paycheck arrived. You looked at it for a long time before spending any of it.', effects: { happiness: 3 } }),
  ev({ id: 'coworkerLunch', category: 'career', needs: ['fullTime'], cooldown: 4, family: 'coworkerBond',
    text: (c) => `A coworker at ${c.employer} invited you to lunch, and you found out you have a lot in common.`, effects: { newCoworker: true, happiness: 2 } }),
  ev({ id: 'coworkerFriendship', category: 'friendship', needs: ['fullTime'], person: 'coworker', cooldown: 4, family: 'coworkerBond',
    text: (c) => `You and ${c.whoName} started grabbing coffee before every shift.`, effects: { closeness: 5, happiness: 2 } }),
  ev({ id: 'bossPraise', category: 'career', needs: ['fullTime', 'goodWork'], cooldown: 3, kind: 'positive', family: 'workReview',
    text: 'Your manager singled out your work in the team meeting.', effects: { happiness: 3, performance: 2 } }),
  ev({ id: 'bossCritique', category: 'career', needs: ['fullTime', 'badWork'], cooldown: 3, family: 'workReview',
    text: 'Your manager pulled you aside about missed deadlines.', effects: { happiness: -3 } }),
  ev({ id: 'bigProject', category: 'career', needs: ['fullTime'], cooldown: 4, family: 'workLoad',
    text: (c) => `${c.employer} put you on a big project. It ate your evenings for months.`, effects: { performance: 4, happiness: -2, health: -1, smarts: 1 } }),
  ev({ id: 'quietYearAtWork', category: 'career', needs: ['fullTime'], cooldown: 4, family: 'workLoad',
    text: 'Work was calm this year, and you actually took your lunch breaks.', effects: { happiness: 2, health: 1 } }),
  ev({ id: 'workTraining', category: 'career', needs: ['fullTime'], cooldown: 4,
    text: (c) => `${c.employer} sent you on a training course. The slides were dull; the skills were useful.`, effects: { smarts: 2, performance: 2 } }),
  ev({ id: 'yearEndBonus', category: 'finance', needs: ['fullTime', 'goodWork'], cooldown: 3, kind: 'positive',
    text: (c) => `A year-end bonus landed in your account thanks to a strong year at ${c.employer}.`, effects: { money: 900, happiness: 3 } }),
  ev({ id: 'workMistake', category: 'career', needs: ['fullTime'], cooldown: 5, weight: 0.8,
    text: 'You made a mistake at work that took a whole week to untangle.', effects: { performance: -4, happiness: -3 } }),
  ev({ id: 'newManager', category: 'career', needs: ['fullTime'], cooldown: 6,
    text: 'You got a new manager who reorganized everything, including where the mugs go.', effects: { happiness: -1 } }),
  ev({ id: 'officeMove', category: 'career', needs: ['fullTime'], cooldown: 8, max: 2,
    text: (c) => `${c.employer} moved to a new office with better light and worse parking.`, effects: { happiness: 1 } }),
  ev({ id: 'companyPicnic', category: 'career', needs: ['fullTime'], cooldown: 4, family: 'workSocial',
    text: 'The company picnic featured a three-legged race that your team lost gracefully.', effects: { happiness: 2, friends: 1 } }),
  ev({ id: 'teamWin', category: 'career', needs: ['fullTime'], cooldown: 4, kind: 'positive', family: 'workSocial',
    text: 'Your team hit its biggest target of the year, and everyone went out to celebrate.', effects: { happiness: 3, performance: 2 } }),
  ev({ id: 'longCommute', category: 'career', needs: ['fullTime', 'noCar'], minAge: 22, cooldown: 6,
    text: 'Your commute stretched to over an hour each way after the bus routes changed.', effects: { happiness: -2, health: -1 } }),
  ev({ id: 'workFromHome', category: 'career', needs: ['fullTime'], cooldown: 6, max: 2,
    text: 'You worked from home for part of the year and discovered your pet has strong opinions about meetings.', effects: { happiness: 2 } }),
  ev({ id: 'mentorAtWork', category: 'career', needs: ['fullTime'], once: true, kind: 'positive',
    text: 'A senior colleague became your mentor and taught you the things no manual covers.', effects: { smarts: 3, performance: 3, newCoworker: true } }),
  ev({ id: 'industryConference', category: 'career', needs: ['fullTime', 'smart'], cooldown: 5,
    text: 'You spoke at an industry conference and only lost your place once.', effects: { smarts: 2, performance: 3, happiness: 2 } }),
  ev({ id: 'headhunter', category: 'career', needs: ['fullTime', 'goodWork'], minAge: 25, cooldown: 8,
    text: 'A recruiter reached out about another company. You felt flattered and stayed put.', effects: { happiness: 2 } }),
  ev({ id: 'workStress', category: 'health', needs: ['fullTime'], cooldown: 4, weight: 0.8,
    text: 'Stress at work started following you home.', effects: { health: -2, happiness: -3 } }),
  ev({ id: 'partTimeShifts', category: 'career', needs: ['employed'], when: (c) => c.employed && c.career.careerId && ['babysitter', 'cashier', 'tutor', 'lifeguard'].includes(c.career.careerId), cooldown: 2,
    text: 'You picked up extra shifts at your part-time job and saved most of it.', effects: { money: 300, happiness: 1, health: -1 } }),
  ev({ id: 'jobSearchSlow', category: 'career', needs: ['unemployedAdult'], minAge: 19, cooldown: 3,
    text: 'You sent out applications all year and heard back from very few of them.', effects: { happiness: -3 } }),
  ev({ id: 'jobSearchTip', category: 'career', needs: ['unemployedAdult'], minAge: 19, person: 'friend', cooldown: 4,
    text: (c) => `${c.whoName} helped you polish your résumé and practice interview answers.`, effects: { smarts: 1, closeness: 3, happiness: 1 } }),
  ev({ id: 'workAnniversary', category: 'career', needs: ['fullTime'], when: (c) => c.career.tenure > 0 && c.career.tenure % 5 === 0, cooldown: 4, kind: 'positive',
    text: (c) => `You celebrated ${c.career.tenure} years at ${c.employer}. There was cake.`, effects: { happiness: 2 } }),
  ev({ id: 'workFriendLeaves', category: 'friendship', needs: ['fullTime'], person: 'coworker', cooldown: 6, weight: 0.6,
    text: (c) => `${c.whoName} left ${c.employer} for a new job. You promised to keep the coffee tradition going.`, effects: { closeness: -2, happiness: -1 } }),
  ev({ id: 'volunteerAtWork', category: 'personal', needs: ['fullTime'], cooldown: 5,
    text: 'You organized a volunteer day for your team at a community garden.', effects: { happiness: 3, friends: 1 } }),
  ev({ id: 'workGadget', category: 'asset', needs: ['fullTime'], cooldown: 6,
    text: (c) => `${c.employer} gave you a new laptop. The old one had a key missing.`, effects: { happiness: 1, smarts: 1 } }),
  ev({ id: 'healthInsuranceWin', category: 'health', needs: ['fullTime'], cooldown: 6,
    text: 'Your workplace health plan covered a checkup you had been putting off.', effects: { health: 3 } }),
];

