// Ages 4-12: childhood and the preteen years. Original BetLife writing.
import { ev } from './define.js';
import { makeEnemy, addStepParent } from '../people.js';
import { info } from '../journal.js';

const C = ['child'];
const CP = ['child', 'preteen'];

export const CHILD_EVENTS = [
  // Playground and neighborhood
  ev({ id: 'scrapedKnee', category: 'health', stages: CP, cooldown: 4, max: 2, family: 'playgroundBump',
    text: 'You scraped your knee coming off the slide too fast. A bandage with cartoon stars fixed everything.', effects: { health: -1, happiness: -1 } }),
  ev({ id: 'treeClimb', category: 'hobby', stages: CP, minAge: 6, cooldown: 5, max: 2, family: 'playgroundBump',
    text: 'You climbed the tallest tree on the street and needed a little help getting down.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'lostTooth', category: 'personal', stages: C, minAge: 5, maxAge: 8, once: true, kind: 'positive',
    text: 'You lost your first tooth and found a coin under your pillow the next morning.', effects: { happiness: 2, money: 5 } }),
  ev({ id: 'learnedToSwim', category: 'hobby', stages: C, minAge: 5, maxAge: 9, once: true, kind: 'positive',
    text: 'You learned to swim at the community pool and refused to leave the deep end.', effects: { happiness: 2, health: 3 } }),
  ev({ id: 'trainingWheels', category: 'hobby', stages: C, minAge: 5, maxAge: 8, once: true, kind: 'positive',
    text: 'You rode a bike without training wheels for the first time, wobbling all the way to the corner.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'snowDay', category: 'hobby', stages: CP, cooldown: 5, max: 2,
    text: 'A surprise snow day closed the schools. You built a lopsided snow fort and defended it all afternoon.', effects: { happiness: 3 } }),
  ev({ id: 'lemonadeStand', category: 'finance', stages: CP, minAge: 7, once: true, kind: 'positive',
    text: 'You ran a lemonade stand on a hot Saturday and made your first money.', effects: { money: 18, smarts: 1, happiness: 2 } }),
  ev({ id: 'neighborhoodGame', category: 'friendship', stages: CP, minAge: 6, person: 'friend', cooldown: 4, family: 'friendPlay',
    text: (c) => `You and ${c.whoName} invented a game with three balls and a bucket that nobody else understood.`, effects: { happiness: 3, closeness: 4 } }),
  ev({ id: 'sleepover', category: 'friendship', stages: CP, minAge: 7, person: 'friend', cooldown: 4, family: 'friendPlay',
    text: (c) => `You had a sleepover at ${c.whoName}'s house and nobody slept before two in the morning.`, effects: { happiness: 3, closeness: 4, health: -1 } }),
  ev({ id: 'parkFriend', category: 'friendship', stages: C, minAge: 4, maxAge: 7, once: true, kind: 'positive',
    text: 'You met another kid at the park and by the end of the afternoon you were inseparable.', effects: { newFriend: true, happiness: 2 } }),

  // Home and family
  ev({ id: 'familyMovieNight', category: 'family', stages: CP, cooldown: 4, family: 'familyFun',
    text: 'Friday movie nights became a family tradition, complete with an argument about the popcorn.', effects: { happiness: 2, family: 2 } }),
  ev({ id: 'campingTrip', category: 'family', stages: CP, minAge: 5, cooldown: 5, max: 2, kind: 'positive', family: 'familyFun',
    text: 'Your family went camping for a weekend. Someone forgot the tent poles, and it became the best story of the summer.', effects: { happiness: 3, health: 1, family: 2 } }),
  ev({ id: 'roadTrip', category: 'family', stages: CP, minAge: 6, cooldown: 6, max: 2, family: 'familyFun',
    text: 'Your family drove for hours to visit relatives. You counted 41 cows and lost a game of I Spy.', effects: { happiness: 2, family: 1 } }),
  ev({ id: 'parentsSeparate', category: 'family', minAge: 1, maxAge: 14, once: true, weight: 0.5, kind: 'negative', when: (c) => c.mother && c.father && !c.state.flags.parentsSeparated,
    text: 'Your parents decided to separate. They both promised nothing would change for you, and mostly kept that promise.', effects: { happiness: -4 },
    then: (state) => { state.flags.parentsSeparated = true; } }),
  ev({ id: 'parentRemarries', category: 'family', minAge: 2, maxAge: 17, cooldown: 3, max: 2, weight: 3, person: (c) => c.state.flags.parentsSeparated ? c.parents.filter((p) => (p.role === 'mother' || p.role === 'father') && !p.remarried) : [],
    text: (c) => `${c.whoName} got married again. You gained a ${c.who.role === 'mother' ? 'stepfather' : 'stepmother'}.`, kind: 'milestone',
    then: (state, c) => { if (c.who) { c.who.remarried = true; const step = addStepParent(state, c.who.role); info(state, 'A New Family Member', `${c.whoName} married ${step.name}. Welcome your new ${step.role === 'stepmother' ? 'stepmother' : 'stepfather'}.`, { band: 'Family', tone: 'green', person: step.id, facts: [['Name', step.name], ['Relationship', step.role === 'stepmother' ? 'Stepmother' : 'Stepfather'], ['Occupation', step.occupation]] }); } } }),
  ev({ id: 'eyeExamCheck', category: 'health', minAge: 7, maxAge: 40, cooldown: 8, max: 2, weight: 0.8, band: 'Healthcare', title: 'Eyesight', when: (c) => !c.glasses,
    text: 'Your eyesight seems to be getting worse. Your parents booked an eye exam: find the odd character before time runs out.', minigame: 'eyeExam' }),
  ev({ id: 'schoolRival', category: 'friendship', stages: ['child', 'preteen', 'teen'], minAge: 8, once: true, weight: 2.5, needs: ['school'],
    text: 'A kid at school decided you were the competition. Every group project turned into a contest.', effects: { happiness: -2 },
    then: (state) => { const e = makeEnemy(state, { age: state.player.age + 1, occupation: 'student' }); state.timeline.push({ age: state.player.age, text: `${e.name} became your rival.`, kind: 'negative' }); } }),
  ev({ id: 'parentsArgue', category: 'family', stages: CP, minAge: 5, cooldown: 6, max: 2, when: (c) => c.mother && c.father,
    text: 'Your parents argued about money one evening. They made up, but you noticed.', effects: { happiness: -2 } }),
  ev({ id: 'helpedCooking', category: 'family', stages: CP, minAge: 6, person: 'parent', cooldown: 5,
    text: (c) => `You helped ${c.whoName} cook dinner and only broke one egg on the floor.`, effects: { smarts: 1, closeness: 3 } }),
  ev({ id: 'siblingRivalry', category: 'family', stages: CP, minAge: 5, person: 'sibling', cooldown: 4,
    text: (c) => `You and ${c.whoName} fought over the remote for a week, then teamed up against bedtime.`, effects: { closeness: 1, happiness: 1 } }),
  ev({ id: 'siblingDefends', category: 'family', stages: CP, minAge: 6, person: 'sibling', once: true, kind: 'positive',
    text: (c) => `${c.whoName} stood up for you when an older kid was being unkind.`, effects: { closeness: 6, happiness: 2 } }),
  ev({ id: 'chores', category: 'family', stages: CP, minAge: 7, once: true,
    text: 'You got your first chores: feeding the plants and pretending to make your bed.', effects: { smarts: 1, money: 10 } }),
  ev({ id: 'petArrives', category: 'family', stages: C, minAge: 4, maxAge: 9, once: true, needs: ['noPets'], weight: 0.7,
    text: '', effects: { newPet: true, happiness: 3 } }),
  ev({ id: 'petTrick', category: 'family', stages: CP, person: 'pet', cooldown: 4,
    text: (c) => `You taught ${c.who.name} a trick. It works about half the time.`, effects: { closeness: 5, happiness: 2 } }),

  // School (elementary)
  ev({ id: 'goldStar', category: 'education', stages: C, needs: ['elementary'], cooldown: 3, max: 3, kind: 'positive', family: 'classWin',
    text: 'Your teacher pinned your drawing on the wall for the whole class to see.', effects: { happiness: 2, performance: 2 } }),
  ev({ id: 'readingLevel', category: 'education', stages: C, needs: ['elementary'], minAge: 6, once: true, kind: 'positive', family: 'classWin',
    text: 'You finished the reading challenge ahead of everyone in your grade.', effects: { smarts: 3, performance: 3 } }),
  ev({ id: 'showAndTell', category: 'education', stages: C, needs: ['elementary'], cooldown: 4, max: 2,
    text: 'For show and tell you brought a rock you were convinced was a dinosaur egg.', effects: { happiness: 2 } }),
  ev({ id: 'classroomPetDuty', category: 'education', stages: C, needs: ['elementary'], once: true,
    text: 'You were trusted with the classroom hamster for a weekend, and it survived.', effects: { happiness: 2, smarts: 1 } }),
  ev({ id: 'fieldTripMuseum', category: 'education', stages: CP, needs: ['school'], cooldown: 5, max: 2, family: 'fieldTrip',
    text: 'Your class took a field trip to the science museum, and you got lost in the space exhibit.', effects: { smarts: 2, happiness: 2 } }),
  ev({ id: 'fieldTripFarm', category: 'education', stages: C, needs: ['elementary'], once: true, family: 'fieldTrip',
    text: 'On a field trip to a farm you fed a goat that tried to eat your worksheet.', effects: { happiness: 3 } }),
  ev({ id: 'multiplicationTables', category: 'education', stages: C, needs: ['elementary'], minAge: 7, once: true,
    text: 'You finally memorized the multiplication tables after weeks of practice.', effects: { smarts: 3, performance: 3 } }),
  ev({ id: 'forgotHomework', category: 'education', stages: CP, needs: ['school'], cooldown: 4, family: 'schoolSlip',
    text: 'You forgot your homework at home and had to explain it to the teacher. Twice.', effects: { performance: -3, happiness: -1 } }),
  ev({ id: 'substituteTeacher', category: 'education', stages: CP, needs: ['school'], cooldown: 5,
    text: 'A substitute teacher let the class watch a documentary about volcanoes. You learned a lot.', effects: { smarts: 1, happiness: 1 } }),
  ev({ id: 'newStudentFriend', category: 'friendship', stages: CP, needs: ['school'], cooldown: 5, max: 2, kind: 'positive',
    text: 'A new student joined your class, and you were the first to show them around.', effects: { newFriend: true, happiness: 1 } }),
  ev({ id: 'spellingWin', category: 'education', stages: CP, needs: ['school', 'smart'], minAge: 8, once: true, kind: 'positive',
    text: 'You won the class spelling contest with a word you could barely say.', effects: { smarts: 2, happiness: 3, performance: 3 } }),
  ev({ id: 'scienceKit', category: 'hobby', stages: CP, minAge: 7, once: true, kind: 'positive',
    text: 'You got a science kit for your birthday and spent weeks growing crystals on the windowsill.', effects: { smarts: 3, happiness: 2 } }),
  ev({ id: 'libraryCard', category: 'hobby', stages: C, minAge: 6, once: true,
    text: 'You got your own library card and checked out more books than you could carry.', effects: { smarts: 2, happiness: 1 } }),

  // Preteen years
  ev({ id: 'middleSchoolLocker', category: 'education', stages: ['preteen'], needs: ['middleSchool'], when: (c) => c.edu.year === 6, weight: 8, once: true,
    text: 'You spent your first week of middle school unable to open your locker.', effects: { happiness: -1, smarts: 1 } }),
  ev({ id: 'scienceFair', category: 'education', stages: ['preteen', 'teen'], needs: ['school'], minAge: 10, maxAge: 15, once: true, kind: 'positive',
    text: 'Your science fair project on plant growth earned an honorable mention.', effects: { smarts: 3, performance: 4, happiness: 2 } }),
  ev({ id: 'groupProject', category: 'education', stages: ['preteen', 'teen'], needs: ['school'], cooldown: 4, family: 'schoolWork',
    text: 'Your class was assigned a big group project, and you ended up doing most of it.', effects: { smarts: 2, performance: 3, happiness: -1 } }),
  ev({ id: 'popQuiz', category: 'education', stages: ['preteen', 'teen'], needs: ['school'], cooldown: 3, family: 'schoolWork',
    text: (c) => (c.edu.performance >= 65 ? 'A surprise quiz caught the class off guard, but you had actually done the reading.' : 'A surprise quiz caught you completely unprepared.'),
    effects: {}, then: null }),
  ev({ id: 'bandTryout', category: 'hobby', stages: ['preteen', 'teen'], needs: ['school'], minAge: 10, maxAge: 15, once: true,
    text: 'You tried out for the school band and got the triangle. You played it with pride.', effects: { happiness: 2, newFriend: true } }),
  ev({ id: 'firstPhone', category: 'asset', stages: ['preteen'], minAge: 11, once: true, kind: 'positive',
    text: 'Your parents gave you your first phone, with a long list of rules attached.', effects: { happiness: 3 } }),
  ev({ id: 'growthSpurt', category: 'health', stages: ['preteen', 'teen'], minAge: 11, maxAge: 15, once: true,
    text: 'You had a growth spurt and none of your pants fit anymore.', effects: { looks: 2, health: 1 } }),
  ev({ id: 'braces', category: 'health', stages: ['preteen', 'teen'], minAge: 11, maxAge: 14, once: true, weight: 0.7,
    text: 'You got braces. Two years of careful chewing began.', effects: { looks: -1, happiness: -2 } }),
  ev({ id: 'bracesOff', category: 'health', stages: ['preteen', 'teen'], minAge: 13, maxAge: 17, once: true, kind: 'positive', when: (c) => (c.state.events.count.braces || 0) > 0,
    text: 'The braces came off, and you could not stop smiling at your reflection.', effects: { looks: 4, happiness: 3 } }),
  ev({ id: 'firstCrush', category: 'personal', stages: ['preteen', 'teen'], minAge: 11, maxAge: 14, once: true,
    text: 'You developed a crush on a classmate and could not say a full sentence in their presence.', effects: { happiness: 1 } }),
  ev({ id: 'embarrassingMoment', category: 'personal', stages: ['preteen', 'teen'], needs: ['school'], cooldown: 5, max: 2,
    text: 'You tripped in front of the whole cafeteria. Everyone forgot about it in a week; you did not.', effects: { happiness: -2 } }),
  ev({ id: 'birthdayParty', category: 'family', stages: CP, minAge: 5, cooldown: 3, family: 'birthday',
    text: (c) => (c.friends.length ? 'Your birthday party had a piñata, and your friends went home covered in candy.' : 'Your family threw you a small birthday party with your favorite cake.'),
    effects: { happiness: 3, friends: 2 } }),
  ev({ id: 'birthdayGiftMoney', category: 'finance', stages: CP, minAge: 6, cooldown: 3, family: 'birthday',
    text: 'A relative sent birthday money in a card with far too much glitter.', effects: { money: 25, happiness: 1 } }),
  ev({ id: 'chickenPox', category: 'health', stages: C, minAge: 4, maxAge: 9, once: true, weight: 0.6,
    text: 'You caught chickenpox and spent a week itching and watching cartoons.', effects: { health: -3, happiness: -1 } }),
  ev({ id: 'glasses', category: 'health', stages: CP, minAge: 7, once: true, weight: 0.6,
    text: 'An eye exam showed you needed glasses. The board at school suddenly made sense.', effects: { smarts: 2, performance: 2 } }),
  ev({ id: 'talentedDrawing', category: 'hobby', stages: CP, minAge: 6, once: true,
    text: 'You filled an entire sketchbook with drawings of dragons and your pet.', effects: { happiness: 2, smarts: 1 } }),
  ev({ id: 'videoGameTournament', category: 'hobby', stages: ['preteen', 'teen'], minAge: 10, person: 'friend', cooldown: 5,
    text: (c) => `You and ${c.whoName} entered a video game tournament and lost in the first round, laughing.`, effects: { happiness: 2, closeness: 3 } }),
];
