// Money, belongings and the rare surprise, for any adult. Original writing.
import { ev } from './define.js';

export const FINANCE_EVENTS = [
  ev({ id: 'smallInheritance', category: 'finance', minAge: 25, cooldown: 15, max: 1, weight: 0.4, kind: 'positive',
    text: 'A distant relative left you a small inheritance and a box of very old postcards.', effects: { money: 3000, happiness: 2 } }),
  ev({ id: 'raffleWin', category: 'rare', minAge: 16, cooldown: 12, max: 1, weight: 0.3, kind: 'positive',
    text: 'You won a raffle at a community fair: a weekend getaway and a giant stuffed bear.', effects: { happiness: 4, money: 200 } }),
  ev({ id: 'localNews', category: 'rare', minAge: 10, cooldown: 15, max: 1, weight: 0.3, kind: 'positive',
    text: 'You ended up in the local news for helping return a lost dog to its owner.', effects: { happiness: 4 } }),
  ev({ id: 'powerOutage', category: 'rare', minAge: 5, cooldown: 10, weight: 0.4,
    text: 'A storm knocked out the power for two days. You played cards by candlelight.', effects: { happiness: 1, family: 1 } }),
  ev({ id: 'phoneBroke', category: 'asset', minAge: 14, cooldown: 5, weight: 0.8,
    text: 'You dropped your phone, and the screen turned into a spiderweb.', effects: { money: -150, happiness: -2 } }),
  ev({ id: 'bikeStolen', category: 'asset', minAge: 8, when: (c) => c.state.assets.some((a) => a.kind === 'bike'), cooldown: 8, weight: 0.5, kind: 'negative',
    text: 'Your bike was stolen from outside the store. You bought a much bigger lock for the next one.', effects: { happiness: -3 },
    then: (state) => { const i = state.assets.findIndex((a) => a.kind === 'bike'); if (i >= 0) state.assets.splice(i, 1); } }),
  ev({ id: 'sideGig', category: 'finance', minAge: 18, needs: ['smart'], cooldown: 5,
    text: 'You did some freelance work on the side and earned a bit of extra money.', effects: { money: 700, smarts: 1, health: -1 } }),
  ev({ id: 'sellOldStuff', category: 'finance', minAge: 16, cooldown: 6,
    text: 'You sold a pile of old things online and cleared out a closet.', effects: { money: 120, happiness: 1 } }),
  ev({ id: 'charityDonation', category: 'personal', minAge: 20, needs: ['money'], cooldown: 5,
    text: 'You donated to a cause you care about and felt lighter for it.', effects: { money: -100, happiness: 3 } }),
  ev({ id: 'investmentGain', category: 'finance', minAge: 25, needs: ['rich'], cooldown: 4, kind: 'positive', family: 'investing',
    text: 'Your savings had a good year, and the interest added up nicely.', effects: { money: 2500, happiness: 2 } }),
  ev({ id: 'investmentDip', category: 'finance', minAge: 25, needs: ['rich'], cooldown: 4, weight: 0.7, family: 'investing',
    text: 'A wobbly market took a bite out of your savings this year.', effects: { money: -1800, happiness: -2 } }),
  ev({ id: 'debtStress', category: 'finance', minAge: 18, needs: ['debt'], cooldown: 2,
    text: 'The debt hung over you all year.', effects: { happiness: -3, health: -1 } }),
  ev({ id: 'homeAppreciation', category: 'asset', minAge: 25, needs: ['home'], cooldown: 6, kind: 'positive',
    text: 'Property values in your neighborhood went up, and your home is worth more than you paid.', effects: { happiness: 2 } }),
  ev({ id: 'carWash', category: 'asset', minAge: 18, needs: ['car'], cooldown: 6, family: 'carFun',
    text: 'You spent a Sunday washing and waxing your car until it gleamed.', effects: { happiness: 2 } }),
  ev({ id: 'jewelryCompliment', category: 'personal', minAge: 18, when: (c) => c.state.assets.some((a) => a.kind === 'jewelry'), cooldown: 5,
    text: 'A stranger stopped you to compliment your jewelry.', effects: { happiness: 2, looks: 1 } }),
  ev({ id: 'instrumentGig', category: 'hobby', minAge: 14, when: (c) => c.state.assets.some((a) => a.kind === 'instrument'), cooldown: 5, kind: 'positive',
    text: 'You played your instrument at a small local event, and people actually clapped.', effects: { happiness: 4, money: 80 } }),
  ev({ id: 'gamingNight', category: 'hobby', minAge: 10, when: (c) => c.state.assets.some((a) => a.kind === 'gadget'), cooldown: 4,
    text: 'You hosted a game night that ran until everyone was too tired to argue about the rules.', effects: { happiness: 3, friends: 2 } }),
  ev({ id: 'cityFestival', category: 'personal', minAge: 6, cooldown: 5,
    text: 'The city festival came around, and you went for the fireworks and stayed for the food.', effects: { happiness: 3 } }),
  ev({ id: 'rainyWeek', category: 'personal', minAge: 4, cooldown: 6, weight: 0.5,
    text: 'It rained for two weeks straight, and you finished every puzzle in the house.', effects: { smarts: 1, happiness: -1 } }),
  ev({ id: 'heatwave', category: 'health', minAge: 4, cooldown: 6, weight: 0.5,
    text: 'A heatwave made the whole city move slowly for a month.', effects: { health: -1, happiness: -1 } }),
];
