// Ages 0-3: babies and toddlers. Original BetLife writing.
import { ev } from './define.js';

const S = ['infant'];

export const INFANT_EVENTS = [
  ev({ id: 'firstSmile', category: 'family', stages: S, maxAge: 1, once: true, kind: 'positive', person: 'parent',
    text: (c) => `You smiled for the first time, and ${c.whoName} would not stop talking about it.`, effects: { happiness: 2, closeness: 3 } }),
  ev({ id: 'firstWord', category: 'family', stages: S, minAge: 1, maxAge: 2, once: true, kind: 'positive',
    text: (c) => `You said your first word${c.mother ? `, and it sounded a lot like "${c.mother.gender === 'female' ? 'mama' : 'dada'}"` : ''}.`, effects: { happiness: 2, smarts: 2 } }),
  ev({ id: 'firstSteps', category: 'family', stages: S, minAge: 1, maxAge: 2, once: true, kind: 'positive',
    text: 'You took your first wobbly steps across the living room and landed on your bottom, laughing.', effects: { happiness: 2, health: 1 } }),
  ev({ id: 'sleeplessNights', category: 'family', stages: S, maxAge: 1, once: true,
    text: 'You kept the whole house awake for weeks. Your parents looked exhausted but never complained.', effects: { family: 1 } }),
  ev({ id: 'favoriteBlanket', category: 'personal', stages: S, minAge: 1, maxAge: 3, once: true,
    text: 'You chose a favorite blanket and refused to sleep without it.', effects: { happiness: 2 } }),
  ev({ id: 'grandparentsVisit', category: 'family', stages: ['infant', 'child'], minAge: 1, maxAge: 9, cooldown: 4, max: 3, kind: 'positive', family: 'grandparents',
    text: 'Your grandparents came to visit and spoiled you for an entire week.', effects: { happiness: 3, family: 2 } }),
  ev({ id: 'grandparentsPhotos', category: 'family', stages: ['infant', 'child'], minAge: 1, maxAge: 8, cooldown: 5, max: 2, family: 'grandparents',
    text: 'Your grandparents sent an album full of photos of you, captioned in wobbly handwriting.', effects: { happiness: 1, family: 1 } }),
  ev({ id: 'babyCold', category: 'health', stages: S, cooldown: 3, max: 2,
    text: 'You caught a cold and spent a few days being carried around the house.', effects: { health: -2, happiness: -1, family: 1 } }),
  ev({ id: 'firstBirthdayCake', category: 'family', stages: S, minAge: 1, maxAge: 1, once: true, kind: 'positive',
    text: 'On your first birthday you put both hands straight into the cake.', effects: { happiness: 3 } }),
  ev({ id: 'peekaboo', category: 'family', stages: S, maxAge: 2, once: true, person: 'parent',
    text: (c) => `${c.whoName} played peekaboo with you until you both had the hiccups from laughing.`, effects: { happiness: 2, closeness: 3 } }),
  ev({ id: 'stackingBlocks', category: 'hobby', stages: S, minAge: 1, maxAge: 3, once: true,
    text: 'You stacked six blocks into a tower before knocking it down with great satisfaction.', effects: { smarts: 2, happiness: 1 } }),
  ev({ id: 'scribbleArt', category: 'hobby', stages: S, minAge: 2, maxAge: 3, once: true,
    text: 'You decorated the hallway wall with crayons. Your parents were not thrilled, but they kept a photo.', effects: { happiness: 2, family: -1 } }),
  ev({ id: 'daycareStart', category: 'lifeStage', stages: S, minAge: 2, maxAge: 3, once: true, kind: 'milestone',
    text: 'You started going to daycare and cried for exactly one morning before deciding it was fun.', effects: { happiness: 1, smarts: 1 } }),
  ev({ id: 'daycareFriend', category: 'friendship', stages: S, minAge: 2, maxAge: 3, once: true, kind: 'positive',
    text: 'At daycare you kept sharing snacks with the same kid, and that is how your first friendship began.', effects: { newFriend: true, happiness: 2 } }),
  ev({ id: 'siblingBorn', category: 'family', stages: ['infant', 'child'], minAge: 1, maxAge: 7, once: true, weight: 0.8, when: (c) => c.siblings.length < 2,
    text: '', effects: { newSibling: true, happiness: 2 } }),
  ev({ id: 'olderSiblingHelps', category: 'family', stages: S, minAge: 1, maxAge: 3, person: 'sibling', once: true, kind: 'positive',
    text: (c) => `${c.whoName} taught you how to clap along to songs.`, effects: { closeness: 5, happiness: 2 } }),
  ev({ id: 'familyPetBond', category: 'family', stages: S, minAge: 1, maxAge: 3, person: 'pet', once: true,
    text: (c) => `${c.who.name} started sleeping next to your crib every night.`, effects: { closeness: 6, happiness: 2 } }),
  ev({ id: 'firstHaircut', category: 'personal', stages: S, minAge: 1, maxAge: 3, once: true,
    text: 'You had your first haircut and screamed as if the scissors were dragons.', effects: { looks: 2, happiness: -1 } }),
  ev({ id: 'busyToddler', category: 'personal', stages: S, minAge: 2, maxAge: 3, once: true,
    text: 'You learned to open every cupboard in the kitchen. Child locks appeared the next day.', effects: { smarts: 1 } }),
  ev({ id: 'storyTime', category: 'family', stages: S, minAge: 1, maxAge: 3, cooldown: 2, max: 2, person: 'parent',
    text: (c) => `${c.whoName} read you the same bedtime story every night for a month because you asked for it.`, effects: { smarts: 2, closeness: 3 } }),
  ev({ id: 'parkSwing', category: 'hobby', stages: S, minAge: 2, maxAge: 3, once: true,
    text: 'You discovered the swings at the park and demanded to be pushed higher every single time.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'parentPromotion', category: 'family', stages: ['infant', 'child', 'preteen'], maxAge: 12, person: 'parent', cooldown: 8, max: 2,
    text: (c) => `${c.whoName} was promoted at work and brought home a cake to celebrate.`, effects: { family: 2, happiness: 1 } }),
];
