// Love, partners, marriage and children, at appropriate ages. Original writing.
import { ev } from './define.js';

export const RELATIONSHIP_EVENTS = [
  ev({ id: 'meetSomeone', category: 'relationship', minAge: 19, maxAge: 60, needs: ['noPartner'], cooldown: 3, weight: 1.2, kind: 'positive',
    text: '', effects: { newPartner: true, happiness: 4 } }),
  ev({ id: 'partnerSurprise', category: 'relationship', minAge: 17, person: 'partner', cooldown: 4, family: 'coupleGood',
    text: (c) => `${c.whoName} planned a surprise picnic for your anniversary.`, effects: { closeness: 6, happiness: 4 } }),
  ev({ id: 'partnerTrip', category: 'relationship', minAge: 19, person: 'partner', needs: ['money'], cooldown: 4, family: 'coupleGood',
    text: (c) => `You and ${c.whoName} took a weekend trip and got happily lost in a new city.`, effects: { closeness: 5, happiness: 4, money: -250 } }),
  ev({ id: 'partnerMeetsParents', category: 'relationship', minAge: 17, person: 'partner', needs: ['parents'], once: true,
    text: (c) => `${c.whoName} met your parents. It was awkward for exactly one dinner.`, effects: { closeness: 4, happiness: 2, family: 2 } }),
  ev({ id: 'partnerArgument', category: 'relationship', minAge: 17, person: 'partner', cooldown: 4, family: 'coupleTrouble',
    text: (c) => `You and ${c.whoName} had a serious argument about the future and made up a week later.`, effects: { closeness: -6, happiness: -3 } }),
  ev({ id: 'partnerDistance', category: 'relationship', minAge: 19, person: 'partner', cooldown: 6, weight: 0.7, family: 'coupleTrouble',
    text: (c) => `${c.whoName} took a job in another city for a year. Long-distance was harder than either of you admitted.`, effects: { closeness: -8, happiness: -3 } }),
  ev({ id: 'partnerSupport', category: 'relationship', minAge: 18, person: 'partner', needs: ['unhappy'], cooldown: 3, family: 'coupleGood',
    text: (c) => `${c.whoName} noticed you were struggling and quietly took care of everything for a while.`, effects: { closeness: 5, happiness: 5 } }),
  ev({ id: 'movedInTogether', category: 'relationship', minAge: 20, person: 'partner', when: (c) => c.partner && c.partner.yearsTogether >= 2, once: true, kind: 'milestone',
    text: (c) => `You and ${c.whoName} moved in together and discovered you fold towels differently.`, effects: { closeness: 5, happiness: 4 } }),
  ev({ id: 'partnerProposes', category: 'relationship', minAge: 22, person: 'partner', when: (c) => c.partner && c.partner.role === 'partner' && c.partner.yearsTogether >= 2 && c.partner.closeness >= 55, cooldown: 4, weight: 2.5,
    text: '', choices: [
      { label: 'Say yes', text: (c) => `${c.whoName} proposed, and you said yes. You are engaged!`, effects: { closeness: 8, happiness: 8 }, kind: 'milestone',
        then: (state, c) => { if (c.who) c.who.role = 'fiance'; } },
      { label: 'Ask for more time', text: (c) => `${c.whoName} proposed, and you asked for a little more time. It was a quiet week.`, effects: { closeness: -4, happiness: -3 } },
    ], title: 'A Proposal', text: (c) => `${c.whoName} got down on one knee at your favorite spot and asked you to spend your lives together.` }),
  ev({ id: 'weddingDay', category: 'relationship', minAge: 20, person: 'partner', when: (c) => c.partner && c.partner.role === 'fiance' && c.partner.yearsTogether >= 1, cooldown: 2, weight: 4, kind: 'milestone',
    text: (c) => `You and ${c.whoName} got married in front of everyone you love.`, effects: { closeness: 8, happiness: 10, money: -800 },
    then: (state, c) => { if (c.who) c.who.role = 'spouse'; } }),
  ev({ id: 'babyOnTheWay', category: 'family', minAge: 23, maxAge: 44, needs: ['partner'], when: (c) => (c.spouse || c.partner.yearsTogether >= 3) && c.children.length < 3 && c.partner.closeness >= 50, cooldown: 3, weight: 3,
    text: '', choices: [
      { label: 'Start a family', text: (c) => `You and ${c.whoName} decided the time was right to start a family.`, effects: { newChild: true, partnerCloseness: 6 }, kind: 'milestone' },
      { label: 'Not yet', text: (c) => `You and ${c.whoName} decided to wait a little longer before having children.`, effects: { happiness: 1 } },
    ], title: 'Growing the Family', person: 'partner', text: (c) => `${c.whoName} brought up the idea of having a baby.` }),
  ev({ id: 'childFirstWord', category: 'family', person: (c) => c.children.filter((k) => k.age === 1), cooldown: 1, max: 3, kind: 'positive',
    text: (c) => `${c.whoName} said a first word, and it was not the one you were hoping for.`, effects: { happiness: 4, closeness: 3 } }),
  ev({ id: 'childSchoolPlay', category: 'family', person: (c) => c.children.filter((k) => k.age >= 6 && k.age <= 11), cooldown: 3, family: 'childProud',
    text: (c) => `${c.whoName} played a tree in the school play, and you filmed every second of it.`, effects: { happiness: 4, closeness: 3 } }),
  ev({ id: 'childSick', category: 'family', person: (c) => c.children.filter((k) => k.age < 12), cooldown: 4, weight: 0.7, family: 'childWorry',
    text: (c) => `${c.whoName} caught a nasty bug, and you spent a week of sleepless nights before it passed.`, effects: { happiness: -3, health: -1, closeness: 3 } }),
  ev({ id: 'childTeenPhase', category: 'family', person: (c) => c.children.filter((k) => k.age >= 13 && k.age <= 17), cooldown: 3, family: 'childWorry',
    text: (c) => `${c.whoName} hit the slammed-door years. You remembered doing the same.`, effects: { happiness: -2, closeness: -3 } }),
  ev({ id: 'childGraduates', category: 'family', person: (c) => c.children.filter((k) => k.age === 18), cooldown: 1, max: 3, kind: 'milestone', family: 'childProud',
    text: (c) => `You watched ${c.whoName} graduate from high school and clapped louder than anyone.`, effects: { happiness: 5, closeness: 4 } }),
  ev({ id: 'childAsksAdvice', category: 'family', person: (c) => c.children.filter((k) => k.age >= 15), cooldown: 4,
    text: (c) => `${c.whoName} asked for your advice about a big decision, and actually took it.`, effects: { happiness: 3, closeness: 5 } }),
  ev({ id: 'familyHoliday', category: 'family', needs: ['spouse'], cooldown: 4,
    text: 'The whole family went on holiday together and came back with a thousand photos.', effects: { happiness: 4, partnerCloseness: 4, money: -900 } }),
  ev({ id: 'spouseCareerWin', category: 'relationship', minAge: 24, person: 'partner', needs: ['spouse'], cooldown: 5, family: 'coupleGood',
    text: (c) => `${c.whoName} got a big promotion, and you celebrated with dinner out.`, effects: { closeness: 3, happiness: 3, money: 400 } }),
  ev({ id: 'coupleCounseling', category: 'relationship', minAge: 25, person: 'partner', when: (c) => c.partner && c.partner.closeness < 35, cooldown: 5,
    text: '', choices: [
      { label: 'Go to counseling', text: (c) => `You and ${c.whoName} went to counseling and slowly found your way back to each other.`, effects: { closeness: 15, happiness: 3, money: -300 } },
      { label: 'Work it out alone', text: (c) => `You and ${c.whoName} tried to work things out on your own. It helped a little.`, effects: { closeness: 5 } },
      { label: 'End the relationship', text: (c) => `You and ${c.whoName} decided to go your separate ways.`, effects: { breakUp: true, happiness: -10 }, kind: 'negative' },
    ], title: 'Growing Apart', text: (c) => `Things with ${c.whoName} have been hard for a while, and ${c.whoName} suggested talking to a counselor.` }),
  ev({ id: 'partnerLeaves', category: 'relationship', minAge: 19, person: 'partner', when: (c) => c.partner && c.partner.closeness < 25, cooldown: 4, weight: 0.8, kind: 'negative',
    text: (c) => `${c.whoName} ended the relationship. You had both known for a while.`, effects: { breakUp: true, happiness: -10 } }),
  ev({ id: 'renewedVows', category: 'relationship', minAge: 40, person: 'partner', needs: ['spouse'], when: (c) => c.partner.yearsTogether >= 20, once: true, kind: 'positive',
    text: (c) => `You and ${c.whoName} renewed your vows in the garden with the kids as witnesses.`, effects: { closeness: 8, happiness: 6 } }),
];
