// Ages 65 and up: retirement, family, changing health and reflection. Non-graphic. Original writing.
import { ev } from './define.js';

const S = ['senior'];
const LATE = ['middleAge', 'senior'];

export const SENIOR_EVENTS = [
  ev({ id: 'retirementRoutine', category: 'lifeStage', stages: S, needs: ['retired'], weight: 8, once: true,
    text: 'Your first year of retirement had no alarm clocks and a lot of long breakfasts.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'retirementRestless', category: 'personal', stages: S, needs: ['retired'], cooldown: 5, weight: 0.7,
    text: 'You missed the rhythm of work more than you expected and looked for something to fill the days.', effects: { happiness: -2 } }),
  ev({ id: 'seniorVolunteer', category: 'personal', stages: S, needs: ['retired'], cooldown: 5,
    text: 'You started volunteering at the library, reading to children every Tuesday.', effects: { happiness: 4, smarts: 1 } }),
  ev({ id: 'gardenYears', category: 'hobby', stages: S, cooldown: 4, family: 'seniorHobby',
    text: 'Your garden became the envy of the street.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'seniorWalkingGroup', category: 'health', stages: S, cooldown: 4, family: 'seniorHobby',
    text: 'You joined a morning walking group and made friends who tell the same jokes every day.', effects: { health: 3, happiness: 2, newFriend: true } }),
  ev({ id: 'memoirWriting', category: 'hobby', stages: S, once: true, family: 'seniorHobby',
    text: 'You started writing down the stories of your life for the family.', effects: { happiness: 3, smarts: 2 } }),
  ev({ id: 'seniorTravel', category: 'hobby', stages: S, needs: ['money'], cooldown: 5, weight: 0.8,
    text: 'You took the trip you had postponed for decades.', effects: { happiness: 5, money: -1500 } }),
  ev({ id: 'grandchildBorn', category: 'family', stages: LATE, minAge: 48, person: (c) => c.children.filter((k) => k.age >= 24 && k.age <= 40), cooldown: 4, max: 4, kind: 'milestone', family: 'grandchild',
    text: (c) => `${c.whoName} had a baby. You are a grandparent now, and you cannot stop showing photos.`, effects: { happiness: 6, closeness: 4 } }),
  ev({ id: 'grandchildVisit', category: 'family', stages: S, when: (c) => (c.state.events.count.grandchildBorn || 0) > 0, cooldown: 3, family: 'grandchild',
    text: 'Your grandchildren spent a week with you and left glitter in every room.', effects: { happiness: 4 } }),
  ev({ id: 'childVisitsSenior', category: 'family', stages: S, person: 'child', cooldown: 3, family: 'childContact',
    text: (c) => `${c.whoName} visited for the holidays and fixed everything in the house that beeped.`, effects: { closeness: 5, happiness: 3 } }),
  ev({ id: 'childCareer', category: 'family', stages: LATE, person: (c) => c.children.filter((k) => k.age >= 25 && k.age <= 45), cooldown: 6, family: 'childContact',
    text: (c) => `${c.whoName} was promoted at work and called you first.`, effects: { happiness: 3, closeness: 2 } }),
  ev({ id: 'oldFriendReconnect', category: 'friendship', stages: S, cooldown: 8, max: 2,
    text: 'An old friend you had lost track of found you again, and it was as if no time had passed.', effects: { newFriend: true, happiness: 4 } }),
  ev({ id: 'seniorFriendGone', category: 'friendship', stages: S, person: 'friend', cooldown: 6, weight: 0.6, kind: 'negative',
    text: (c) => `Your friend ${c.whoName} passed away. You spoke at the memorial about the good years.`, effects: { happiness: -8, loseFriend: true } }),
  ev({ id: 'spouseAnniversary', category: 'relationship', stages: LATE, needs: ['spouse'], person: 'partner', when: (c) => c.partner.yearsTogether >= 25 && c.partner.yearsTogether % 5 === 0, cooldown: 4, kind: 'positive',
    text: (c) => `You and ${c.whoName} celebrated ${c.partner.yearsTogether} years together with the whole family.`, effects: { happiness: 5, partnerCloseness: 6 } }),
  ev({ id: 'slowingDown', category: 'health', stages: S, minAge: 70, cooldown: 5,
    text: 'The stairs took a little longer this year.', effects: { health: -2 } }),
  ev({ id: 'hearingAid', category: 'health', stages: S, minAge: 70, once: true, weight: 0.7,
    text: 'You got a hearing aid and discovered the fridge has been humming for years.', effects: { health: 1, happiness: 1 } }),
  ev({ id: 'seniorCheckup', category: 'health', stages: S, cooldown: 3,
    text: 'Your yearly checkup came with new advice and a longer list of vitamins.', effects: { health: 2 } }),
  ev({ id: 'seniorFall', category: 'health', stages: S, minAge: 72, cooldown: 5, weight: 0.7,
    text: 'You took a fall in the garden and needed a few weeks to recover.', effects: { health: -4, happiness: -2 } }),
  ev({ id: 'recoveredWell', category: 'health', stages: S, needs: ['fit'], cooldown: 5,
    text: 'The doctor said you were in remarkable shape for your age.', effects: { happiness: 3, health: 1 } }),
  ev({ id: 'downsizing', category: 'asset', stages: S, needs: ['home'], once: true, weight: 0.6,
    text: 'You thought about moving somewhere smaller and cleared out the attic as a first step.', effects: { happiness: 1, money: 200 } }),
  ev({ id: 'pensionCheck', category: 'finance', stages: S, needs: ['retired'], cooldown: 6,
    text: 'You went through your finances carefully and found they would hold up.', effects: { happiness: 2 } }),
  ev({ id: 'tightPension', category: 'finance', stages: S, needs: ['retired', 'broke'], cooldown: 3,
    text: 'Money was tight on a small pension, and you learned to make do.', effects: { happiness: -3 } }),
  ev({ id: 'legacyGift', category: 'finance', stages: S, needs: ['children', 'rich'], cooldown: 6, kind: 'positive',
    text: 'You helped your children with a generous gift and felt richer for it.', effects: { money: -10000, happiness: 4, family: 3 } }),
  ev({ id: 'lifeLessons', category: 'personal', stages: S, cooldown: 6,
    text: 'A young neighbor asked for your advice, and you realized how much you had learned.', effects: { happiness: 3 } }),
  ev({ id: 'birthdayEighty', category: 'lifeStage', stages: S, minAge: 80, maxAge: 80, weight: 8, once: true, kind: 'milestone',
    text: 'You turned eighty, and the family threw a party with eighty candles and one fire extinguisher.', effects: { happiness: 5 } }),
  ev({ id: 'birthdayNinety', category: 'lifeStage', stages: S, minAge: 90, maxAge: 90, weight: 8, once: true, kind: 'milestone',
    text: 'You turned ninety. The local paper printed your photo.', effects: { happiness: 5 } }),
  ev({ id: 'centenarian', category: 'lifeStage', stages: S, minAge: 100, maxAge: 100, weight: 8, once: true, kind: 'milestone',
    text: 'You turned one hundred years old and received a letter from the mayor.', effects: { happiness: 6 } }),
  ev({ id: 'seniorPetCompanion', category: 'family', stages: S, person: 'pet', cooldown: 4,
    text: (c) => `${c.who.name} kept you company through the long winter evenings.`, effects: { closeness: 4, happiness: 3 } }),
  ev({ id: 'seniorPuzzle', category: 'hobby', stages: S, cooldown: 4, family: 'seniorHobby',
    text: 'You got hooked on crossword puzzles and finished the hardest one of the year.', effects: { smarts: 2, happiness: 2 } }),
  ev({ id: 'quietEvening', category: 'personal', stages: S, cooldown: 4, weight: 0.6,
    text: 'You spent many evenings on the porch, watching the street and feeling content.', effects: { happiness: 2 } }),
  ev({ id: 'seniorMentor', category: 'career', stages: S, needs: ['retired'], when: (c) => c.career.yearsWorked >= 15, once: true,
    text: 'A former colleague asked you to mentor new hires part-time. You said yes for the coffee.', effects: { happiness: 3, smarts: 1, money: 800 } }),
];
