// Ages 13-17: teenagers and high school. Original BetLife writing.
import { ev } from './define.js';

const T = ['teen'];

export const TEEN_EVENTS = [
  // High school life
  ev({ id: 'highSchoolFirstDay', category: 'education', stages: T, needs: ['highSchool'], when: (c) => c.edu.year === 9, weight: 8, once: true,
    text: 'Your first day of high school involved three wrong classrooms and one very patient teacher.', effects: { smarts: 1 } }),
  ev({ id: 'favoriteTeacher', category: 'education', stages: T, needs: ['school'], once: true, kind: 'positive',
    text: 'A teacher noticed you were bored and started lending you harder books.', effects: { smarts: 3, performance: 3, happiness: 2 } }),
  ev({ id: 'toughExams', category: 'education', stages: T, needs: ['highSchool'], cooldown: 3, family: 'schoolWork',
    text: (c) => (c.edu.performance >= 70 ? 'Final exams were brutal, but all that studying paid off.' : 'Final exams were brutal, and you wished you had studied more.'),
    effects: { happiness: -1, smarts: 1 } }),
  ev({ id: 'presentation', category: 'education', stages: T, needs: ['school'], cooldown: 4, family: 'schoolWork',
    text: 'You gave a presentation to the class with shaking hands, and it went better than you feared.', effects: { smarts: 1, performance: 2, happiness: 1 } }),
  ev({ id: 'detention', category: 'education', stages: T, needs: ['school'], cooldown: 5, max: 2, family: 'schoolSlip',
    text: 'You got detention for talking during a test. The room was very quiet.', effects: { performance: -3, happiness: -2 } }),
  ev({ id: 'honorRoll', category: 'education', stages: T, needs: ['highSchool', 'goodGrades'], cooldown: 2, kind: 'positive', family: 'classWin',
    text: 'You made the honor roll, and your name went up on the board by the office.', effects: { happiness: 3, smarts: 1 } }),
  ev({ id: 'failingWarning', category: 'education', stages: T, needs: ['highSchool', 'badGrades'], cooldown: 2, family: 'schoolSlip',
    text: 'A letter came home warning that your grades were slipping.', effects: { happiness: -3 } }),
  ev({ id: 'debateClub', category: 'education', stages: T, needs: ['highSchool'], once: true,
    text: 'You joined the debate club and lost your first debate about pineapple on pizza.', effects: { smarts: 2, newFriend: true } }),
  ev({ id: 'schoolNewspaper', category: 'hobby', stages: T, needs: ['highSchool'], once: true,
    text: 'You wrote an article for the school newspaper about the terrible cafeteria fries.', effects: { smarts: 2, happiness: 2 } }),
  ev({ id: 'schoolDance', category: 'personal', stages: T, needs: ['highSchool'], cooldown: 3, max: 2,
    text: (c) => (c.friends.length ? 'You went to the school dance with your friends and danced badly on purpose.' : 'You went to the school dance and mostly guarded the snack table.'),
    effects: { happiness: 3, friends: 2 } }),
  ev({ id: 'sportsTeamWin', category: 'hobby', stages: T, needs: ['school', 'fit'], cooldown: 3, max: 2, kind: 'positive',
    text: 'Your school team won the regional final, and you were carried off the field.', effects: { happiness: 4, health: 2, newFriend: true } }),
  ev({ id: 'sportsInjury', category: 'health', stages: T, needs: ['school'], cooldown: 5, max: 2, weight: 0.7,
    text: 'You sprained your ankle during gym class and spent two weeks on crutches.', effects: { health: -3, happiness: -2 } }),
  ev({ id: 'theaterProduction', category: 'hobby', stages: T, needs: ['highSchool'], once: true, kind: 'positive',
    text: 'You joined the spring theater production and only forgot one line on opening night.', effects: { happiness: 3, looks: 1, newFriend: true } }),
  ev({ id: 'volunteerDrive', category: 'personal', stages: T, cooldown: 4, max: 2,
    text: 'You helped organize a food drive and filled a whole van with donations.', effects: { happiness: 3, smarts: 1 } }),

  // Friends and social life
  ev({ id: 'bestFriendMoment', category: 'friendship', stages: T, person: (c) => c.friends.filter((f) => f.role === 'friend'), once: true, kind: 'positive',
    text: (c) => `After a long summer of adventures, you and ${c.whoName} became best friends.`, effects: { closeness: 8, happiness: 3, bestFriend: true } }),
  ev({ id: 'friendMoves', category: 'friendship', stages: T, person: 'friend', cooldown: 8, max: 1, weight: 0.5, kind: 'negative',
    text: (c) => `${c.whoName}'s family moved to another city. You promised to stay in touch.`, effects: { happiness: -4, loseFriend: true } }),
  ev({ id: 'friendFallingOut', category: 'friendship', stages: T, person: 'friend', cooldown: 5, family: 'friendTrouble',
    text: (c) => `You and ${c.whoName} did not speak for a month over something neither of you can remember now.`, effects: { closeness: -8, happiness: -3 } }),
  ev({ id: 'friendRoadTrip', category: 'friendship', stages: T, minAge: 16, person: 'friend', cooldown: 4, family: 'friendFun',
    text: (c) => `You and ${c.whoName} spent a whole day exploring the city by bus.`, effects: { closeness: 5, happiness: 3 } }),
  ev({ id: 'gamingMarathon', category: 'friendship', stages: T, person: 'friend', cooldown: 4, family: 'friendFun',
    text: (c) => `You and ${c.whoName} played video games until sunrise and regretted nothing.`, effects: { closeness: 4, happiness: 3, health: -1 } }),
  ev({ id: 'partyInvite', category: 'personal', stages: T, minAge: 15, needs: ['friends'], cooldown: 4,
    text: 'You were invited to a party and spent an hour deciding what to wear.', effects: { happiness: 2, looks: 1 } }),
  ev({ id: 'firstDate', category: 'relationship', stages: T, minAge: 16, needs: ['noPartner'], once: true, weight: 0.8,
    text: 'A classmate asked you to the movies, and you spent the whole film wondering if it counted as a date.', effects: { happiness: 3 } }),
  ev({ id: 'teenRomance', category: 'relationship', stages: T, minAge: 16, needs: ['noPartner'], once: true, weight: 0.8, kind: 'positive',
    text: '', effects: { newPartner: true, happiness: 4 } }),

  // Growing up
  ev({ id: 'partTimeOffer', category: 'finance', stages: T, minAge: 15, needs: ['notRetired'], once: true,
    text: 'A neighbor paid you to mow lawns all summer. Your arms ached, your wallet did not.', effects: { money: 220, health: 1 } }),
  ev({ id: 'savingsAccount', category: 'finance', stages: T, minAge: 14, once: true,
    text: 'You opened your first savings account and stared at the balance for a while.', effects: { smarts: 1 } }),
  ev({ id: 'curfewArgument', category: 'family', stages: T, minAge: 15, person: 'parent', cooldown: 4, family: 'familyFriction',
    text: (c) => `You came home late and had a long talk with ${c.whoName} about curfews.`, effects: { closeness: -3, happiness: -2 } }),
  ev({ id: 'familyVacation', category: 'family', stages: T, cooldown: 5, max: 2, kind: 'positive', family: 'familyFun',
    text: 'Your family took a summer trip to the coast. You pretended not to enjoy it and enjoyed it a lot.', effects: { happiness: 3, family: 2 } }),
  ev({ id: 'parentTeaches', category: 'family', stages: T, person: 'parent', cooldown: 5, family: 'familyLesson',
    text: (c) => `${c.whoName} taught you how to change a tire, budget a paycheck, and stay calm about both.`, effects: { smarts: 2, closeness: 3 } }),
  ev({ id: 'siblingAdvice', category: 'family', stages: T, person: 'sibling', cooldown: 4,
    text: (c) => `${c.whoName} gave you honest advice about school, and it turned out to be right.`, effects: { closeness: 4, smarts: 1 } }),
  ev({ id: 'learnToDrive', category: 'personal', stages: T, minAge: 16, needs: ['noLicence'], person: 'parent', once: true,
    text: (c) => `${c.whoName} took you to an empty parking lot to practice driving. Only one cone was harmed.`, effects: { smarts: 1, closeness: 2 } }),
  ev({ id: 'drivingRoadTrip', category: 'personal', stages: T, minAge: 16, needs: ['licence'], once: true, kind: 'positive',
    text: 'You drove yourself to school for the first time and parked very, very carefully.', effects: { happiness: 3 } }),
  ev({ id: 'skinTrouble', category: 'health', stages: T, once: true, weight: 0.7,
    text: 'A stretch of bad skin made you dread school photos.', effects: { looks: -2, happiness: -2 } }),
  ev({ id: 'styleChange', category: 'personal', stages: T, minAge: 14, once: true,
    text: 'You changed your whole style over one weekend. Some of it worked.', effects: { looks: 2, happiness: 2 } }),
  ev({ id: 'musicDiscovery', category: 'hobby', stages: T, once: true,
    text: 'You discovered a band nobody else at school knew about and played them constantly.', effects: { happiness: 3 } }),
  ev({ id: 'collegeFair', category: 'education', stages: T, minAge: 16, needs: ['highSchool'], once: true,
    text: 'You visited a college fair and came home with a bag full of brochures and big ideas.', effects: { smarts: 1, happiness: 1 } }),
  ev({ id: 'summerCamp', category: 'hobby', stages: ['preteen', 'teen'], minAge: 12, maxAge: 16, once: true, kind: 'positive',
    text: 'You spent two weeks at summer camp and came home sunburned, tired and happy.', effects: { happiness: 4, health: 2, newFriend: true } }),
  ev({ id: 'teenStress', category: 'health', stages: T, needs: ['school'], minAge: 15, cooldown: 4, weight: 0.6,
    text: 'Between school and everything else, you felt stretched thin this year.', effects: { happiness: -3, health: -1 } }),
  ev({ id: 'codingClub', category: 'hobby', stages: T, needs: ['smart'], once: true, kind: 'positive',
    text: 'You joined a coding club and built a tiny game about a bird flying through pipes.', effects: { smarts: 4, happiness: 2 } }),
  ev({ id: 'firstConcert', category: 'hobby', stages: T, minAge: 15, needs: ['money'], once: true,
    text: 'You went to your first concert and lost your voice for two days.', effects: { happiness: 4, money: -40 } }),
];
