// University and trade school years. Original BetLife writing.
import { ev } from './define.js';

export const UNIVERSITY_EVENTS = [
  ev({ id: 'dormLife', category: 'education', needs: ['university'], weight: 8, once: true,
    text: 'You moved into a dorm with a roommate who snores and a view of the parking lot.', effects: { happiness: 1, smarts: 1 } }),
  ev({ id: 'firstLecture', category: 'education', needs: ['university'], once: true,
    text: 'Your first lecture had 300 students and one very quiet microphone.', effects: { smarts: 1 } }),
  ev({ id: 'usedTextbooks', category: 'finance', needs: ['university'], cooldown: 3, family: 'campusMoney',
    text: 'You found used textbooks for a fraction of the price and felt like a genius.', effects: { money: 90, happiness: 1 } }),
  ev({ id: 'campusJob', category: 'finance', needs: ['university'], once: true, family: 'campusMoney',
    text: 'You worked a few shifts a week at the campus café. Free coffee, tired mornings.', effects: { money: 900, health: -1 } }),
  ev({ id: 'allNighter', category: 'education', needs: ['student', 'adult'], cooldown: 3, family: 'campusStudy',
    text: 'You pulled an all-nighter before a big exam and could not remember your own student number.', effects: { performance: 3, health: -2, happiness: -1 } }),
  ev({ id: 'professorPraise', category: 'education', needs: ['university', 'goodGrades'], cooldown: 2, kind: 'positive', family: 'campusWin',
    text: 'A professor read your essay aloud as an example of how it should be done.', effects: { happiness: 3, smarts: 2 } }),
  ev({ id: 'failedMidterm', category: 'education', needs: ['university', 'badGrades'], cooldown: 2, family: 'campusSlip',
    text: 'You failed a midterm and had a serious talk with yourself about study habits.', effects: { happiness: -3, performance: 2 } }),
  ev({ id: 'studyGroupForms', category: 'friendship', needs: ['student', 'adult'], once: true, kind: 'positive',
    text: 'You joined a weekly study group that quickly became a weekly pizza night with occasional studying.', effects: { newFriend: true, performance: 2 } }),
  ev({ id: 'campusClub', category: 'hobby', needs: ['university'], cooldown: 4, max: 2,
    text: 'You joined a campus club and helped organize a charity fun run.', effects: { happiness: 3, newFriend: true } }),
  ev({ id: 'researchProject', category: 'education', needs: ['university', 'smart'], minAge: 19, once: true, kind: 'positive',
    text: 'A professor invited you to help with a research project over the summer.', effects: { smarts: 4, performance: 3, money: 400 } }),
  ev({ id: 'internship', category: 'career', needs: ['university'], minAge: 20, once: true, kind: 'positive',
    text: 'You landed a summer internship and learned what an office actually does all day.', effects: { smarts: 2, money: 1500, happiness: 2 } }),
  ev({ id: 'studyAbroad', category: 'education', needs: ['university'], minAge: 19, once: true, weight: 0.7, kind: 'positive',
    text: 'You spent a semester abroad and came back with new friends and a few words in a new language.', effects: { smarts: 3, happiness: 4, money: -600, newFriend: true } }),
  ev({ id: 'campusFlu', category: 'health', needs: ['student', 'adult'], cooldown: 3, weight: 0.7,
    text: 'The campus flu went around, and you spent a week living on soup.', effects: { health: -3, performance: -2 } }),
  ev({ id: 'tuitionWorry', category: 'finance', needs: ['university', 'debt'], cooldown: 2,
    text: 'You checked your student loan balance and decided not to check it again for a while.', effects: { happiness: -2 } }),
  ev({ id: 'scholarship', category: 'finance', needs: ['university', 'goodGrades'], once: true, weight: 0.6, kind: 'positive',
    text: 'Your grades earned you a small scholarship for the year.', effects: { money: 2500, happiness: 3 } }),
  ev({ id: 'roommateDrama', category: 'personal', needs: ['university'], cooldown: 3,
    text: 'Your roommate adopted a plant, then a fish, then a very loud alarm clock.', effects: { happiness: -1 } }),
  ev({ id: 'campusRomance', category: 'relationship', needs: ['university', 'noPartner'], cooldown: 3, weight: 0.8, kind: 'positive',
    text: '', effects: { newPartner: true, happiness: 4 } }),
  ev({ id: 'thesisDone', category: 'education', needs: ['university'], when: (c) => c.edu.year === 4, weight: 8, once: true, kind: 'positive',
    text: 'You handed in your final project and slept for fourteen hours.', effects: { smarts: 2, happiness: 3 } }),
  ev({ id: 'tradeWorkshop', category: 'education', needs: ['trade'], weight: 8, once: true,
    text: 'Your first workshop class involved real tools and a very serious safety talk.', effects: { smarts: 2 } }),
  ev({ id: 'tradeProject', category: 'education', needs: ['trade'], cooldown: 2,
    text: 'You finished a hands-on project at trade school that actually worked on the first try.', effects: { smarts: 2, performance: 3, happiness: 2 } }),
  ev({ id: 'tradeMentor', category: 'career', needs: ['trade'], once: true, kind: 'positive',
    text: 'An instructor at trade school took you under their wing and offered to write a recommendation.', effects: { smarts: 2, happiness: 2 } }),
  ev({ id: 'campusHackathon', category: 'hobby', needs: ['university', 'smart'], once: true,
    text: 'You stayed up all weekend at a hackathon and built something that almost worked.', effects: { smarts: 3, happiness: 2, newFriend: true } }),
];
